[theme]
base                     = "dark"
primaryColor             = "#CFB991"
backgroundColor          = "#111111"
secondaryBackgroundColor = "#1c1c1c"
textColor                = "#e8e9ed"
font                     = "sans serif"

[server]
headless                    = true
enableCORS                  = false
enableXsrfProtection        = false
enableWebsocketCompression  = false

[browser]
gatherUsageStats = false
