[theme]
base                     = "dark"
primaryColor             = "#CFB991"
backgroundColor          = "#08080f"
secondaryBackgroundColor = "#0f0f1a"
textColor                = "#c0c8d8"
font                     = "sans"

[server]
headless                    = true
enableCORS                  = false
enableXsrfProtection        = false
enableWebsocketCompression  = false

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[logger]
level = "warning"
