[theme]
base                     = "dark"
primaryColor             = "#CFB991"
backgroundColor          = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor                = "#e8e9ed"
font                     = "sans serif"

[server]
headless                    = true
enableCORS                  = false
enableXsrfProtection        = false
enableWebsocketCompression  = false

[browser]
gatherUsageStats = false
